import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            {/* <div className='' style={{width: "100%", height: "500px"}}>
            <Image src="/bigPic.jpg" alt="image" layout='intrinsic' />
            </div> */}
            <div className='m-3'>
                <Link href='/staticSideRender'>
                    <a>Static Side Rendering</a>
                </Link>
            </div>
            <div className='m-3'>
                <Link href='/clientSideRender'>
                    <a>Client Side Rendering</a>
                </Link>
            </div>
            <div className='m-3'>
                <Link href='/serverSideRender'>
                    <a>Server Side Rendering</a>
                </Link>
            </div>
        </div>
    );
}
